name: Playwright Tests

on:
  pull_request:
    branches: [master, development]
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'ENVIRONMENT'
        required: false
        default: 'QA'
      TAG:
        description: 'TAG'
        required: false
        default: ''
      INVERT_TAG:
        description: 'INVERT_TAG'
        required: false
        default: ''
      PROJECT:
        description: 'PROJECT'
        required: false
        default: 'RegressionChrome'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      # VS Code may warn, but this works in GitHub Actions
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT || vars.ENVIRONMENT }}
      TAG: ${{ github.event.inputs.TAG || vars.TAG }}
      INVERT_TAG: ${{ github.event.inputs.INVERT_TAG || vars.INVERT_TAG }}
      PROJECT: ${{ github.event.inputs.PROJECT || vars.PROJECT }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "TAG=$TAG"
          echo "INVERT_TAG=$INVERT_TAG"
          echo "PROJECT=$PROJECT"
          npx cross-env ENVIRONMENT=$ENVIRONMENT \
            playwright test \
            --grep="$TAG" \
            --grep-invert="$INVERT_TAG" \
            --config=./playwright.config.ts \
            --project=$PROJECT
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
